name: Sync LeetCode to GitHub

on:
  workflow_dispatch: # Allows manual trigger anytime
  schedule:
    - cron: '0 18 * * *' # Runs daily at 12 AM IST (18:00 UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync Solutions
        uses: joshcai/leetcode-sync@v1.7.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
